### ISSUE TITLE
How do I authenticate?

### ISSUE THREAD

**Issue by davisagli** [plone/plone.server#3]
Accessing http://localhost:8080 responds with "401: Unauthorized"...what's the next step?

**Comment by bloodbare** [comment]
its a WIP, right now there is no user DB neither system-user and relies on external JWT token auth and oauth delegation. I'm working on a test user infraestructure!

**Comment by davisagli** [comment]
Yeah, so how do I get a token?

David Glick
(mobile)

**Comment by datakurre** [comment]
@davisagli, Ramon and @allusa did open source their github.com/pyrenees/plone.oauth so I'd expect we to have soon a docker-compose file there to setup that as oauth server next to plone.server. Let's give Ramon a day to recover :)

**Comment by allusa** [comment]
We are working on a docker-compose for building alltogether. You can find it at 
http://github.com/pyrenees/docker. Cloning it and running `docker-compose -f ploneNG.yml up` should give at http://localhost:8080 a plone.server running integrated with plone.oauth.

**Comment by bloodbare** [comment]
Hey @davisagli , we added root user so its possible to try it. There is a file in the root (config.json) where DB are defined that are going to be mounted, and the passwd for admin ( in this case is admin also ).

To try it : Authorization header : bearer admin

Its on branch #4  (multidb)

**Comment by davisagli** [comment]
Thanks. Are you adding that header using a browser plugin, or curl, or something else?

**Comment by bloodbare** [comment]
I'm using postman, there is a tests.json (postman collection) on the root that checks creation of sites. you can run them starting a zeo (./bin/runzeo -C zeo.cfg) a server (./bin/server) and newman (newman -c tests.json).

**Comment by bloodbare** [comment]
I don't know if you saw it but there is some docs on the repo ( working on more documentation ) and a pypi release so you try via pip install plone.server && pserver
