### ISSUE TITLE
Should we use local component registry in addons?

### ISSUE THREAD

**Issue by vangheem** [plone/plone.server#34]
Since we can't use thread locals, we aren't using setSite and getSite and then getSiteManager will never return the local site manager as well.

However, it can be useful for addons to provide site-specific functionality, adapters, etc.

A way around this limitation is to have every sort of extendable functionality adapter the "request" objects so registered layers is the way you start hooking in custom functionality.

Thoughts?

If it is not considered good and safe to use the local registry, perhaps we should just remove it and no longer register the settings registry on the local components registry.

`registry` being used in terms confusingly here--hope that all makes sense.

**Comment by bloodbare** [comment]
Right now is just adding overhead on the plone.server. No persistent local components are registered as all the "Sites" share the same ecosystem. As its a thin framework I can't see especific adapters/utility and subscribers for each site as we could easily start different servers for different configurations. 

The only point where it may be needed is for TTW adaptation, but again a far away use case so I'm agree to with the idea.
