### ISSUE TITLE
Code style...

### ISSUE THREAD

**Issue by vangheem** [plone/plone.server#36]
Seems we're forever troubled by the zope style of naming things..

Right now, we have module level functions that are both camel case and many that are underscore.

I'm inclined to stick with the underscore way so we're more pythonic. I know this is annoying with zope tech since it uses camel case.

Thoughts?

**Comment by gforcada** [comment]
💯 keeping Plone's styleguide would be cool.

For the naming conventions [pep8-naming](http://pypi.python.org/pypi/pep8-naming) is what you are looking for :-)

And while at it [yapf](https://github.com/google/yapf) to not have to spend too much time fixing all the linting yourself (I'm looking forward to a webservice that creates pull requests after piping a whole project through yapf).

I could create a pull request adding all that if there's interest.

**Comment by vangheem** [comment]
@gforcada sure! that'd be helpful

**Comment by bloodbare** [comment]
Agree on the underscore python naming.

Great for the pep8-naming!
