### ISSUE TITLE
Is __allow_access__ necessary?

### ISSUE THREAD

**Issue by vangheem** [plone/plone.server#65]
See https://github.com/plone/plone.server/blob/master/src/plone.server/plone/server/browser.py#L35 and https://github.com/plone/plone.server/blob/master/src/plone.server/plone/server/traversal.py#L411 for details

It seems to be that using permissions correctly should already handle this use-case right? Simply using a permission that `plone.Anonymous` is granted should be enough?

Or am I missing something here for why this is necessary? Does it have to do with CORS? In any case, I think we should clear this up.

Also, setting this value maybe should be possible with the `@configure` decorator.

**Comment by bloodbare** [comment]
The use case is quite simple:

You don't have access to an object on the tree, but there is a view who does not publish any information of the object and you want that is able to be accessed based on its own permissions, then the __allow_access__ just lets the traversal go throw the AccessContent check ( remember that no object from the tree is accessible if the user does not have specifc AccessContent to that resource)
