### ISSUE TITLE
Use decorators to define endpoints

### ISSUE THREAD

**Issue by vangheem** [plone/plone.server#9]
@bloodbare 

I think it'd be better for us to use decorators to define endpoints instead of everything in the json file.

What do you think about doing something like this?

```
@Service(
    for_=IDataBase,
    method='GET',
    permission='plone.GetPortals'
)
async def get(context, request):
    serializer = getMultiAdapter((context, request), ISerializeToJson)
    return serializer()
```

**Comment by bloodbare** [comment]
Sorry I missed this  issue, My goal for a file definition is the option to generate something from it.
